name: flutter_travel_budget
description: Um simples aplicativo para controlar custos em uma viagem

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.0
  uuid: ^3.0.6
  fl_chart: ^0.55.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
