// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_aZAqTttZxCyLaIjvNC2XVKReQow_PE',
    appId: '1:22724182094:web:52c0331303a8985ef8c31f',
    messagingSenderId: '22724182094',
    projectId: 'flutter-travels',
    authDomain: 'flutter-travels.firebaseapp.com',
    storageBucket: 'flutter-travels.appspot.com',
    measurementId: 'G-SYTH91045D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9CVybODqorq2s4kZvZFNUzMSATfKJ6no',
    appId: '1:22724182094:android:6a6aa49c8fa02bdbf8c31f',
    messagingSenderId: '22724182094',
    projectId: 'flutter-travels',
    storageBucket: 'flutter-travels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJi-0Axya_u6Ma4l5nG9WqgLcnqmVjyog',
    appId: '1:22724182094:ios:0fe4b9eda06af563f8c31f',
    messagingSenderId: '22724182094',
    projectId: 'flutter-travels',
    storageBucket: 'flutter-travels.appspot.com',
    iosClientId: '22724182094-adi7hud8m3f9r5et7fe1mgi642miboo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJi-0Axya_u6Ma4l5nG9WqgLcnqmVjyog',
    appId: '1:22724182094:ios:0fe4b9eda06af563f8c31f',
    messagingSenderId: '22724182094',
    projectId: 'flutter-travels',
    storageBucket: 'flutter-travels.appspot.com',
    iosClientId: '22724182094-adi7hud8m3f9r5et7fe1mgi642miboo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelBudget',
  );
}
